### ISSUE TITLE
Yii Editable column not initiating on ajax call when filling empty grid.

### ISSUE THREAD

**Issue by jackkitley** [clevertech/YiiBooster#1006] opened 2015-02-10 08:27 UTC
I have a editable grid with columns that can be changed with a popup editable. On default load of data in the grid i can edit the data and the striped underline will show.

When there is no data by default and you bring data into the grid there is a solid blue line and you cant click the value to edit it in the editable popup.

I remember this being an issue that was fixed in an older version when you had to re-register the javascript.

**Comment by jackkitley** [comment] 2015-02-10 08:28
![f03fd5f2-3cc6-11e4-9748-5c1da9b2bf29](https://cloud.githubusercontent.com/assets/3243014/6123794/86e5af42-b10f-11e4-9c26-f501565bf14b.png)
![f03c5b5c-3cc6-11e4-9b5a-86e12ba583dc](https://cloud.githubusercontent.com/assets/3243014/6123796/8bfb0ee6-b10f-11e4-9e6c-f6127514f7f9.png)

**Comment by amrbedair** [comment] 2015-02-10 09:08
@hijarian problem here when the grid is initially empty ... no data ... the editable is not initiated at all ... then some rows added via ajax ... now editable will not work

**Comment by lisps** [comment] 2015-02-10 17:43
this is a duplicate of #949 and #954 never fixed it (because it fixed an other thing).
I described my working solution in the comments at #949.

**Comment by jackkitley** [comment] 2015-02-11 07:40
@lisps Hi! I tried your solution but could never get it working. How hard would a permanent fix be?

**Closed** 2015-03-03 15:34 UTC
